# Generated by Django 6.0.4 on 2026-04-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='employer_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
