# Generated by Django 6.0.4 on 2026-04-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_employer_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='employer_note',
        ),
        migrations.AddField(
            model_name='application',
            name='employer_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
